"""PDF report generation for HealthSense AI predictions."""

import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from src.config import pretty

NAVY = (11, 22, 45)
ACCENT = (56, 132, 255)
DANGER = (214, 69, 69)
SAFE = (39, 174, 96)

NEXT_LINE = {"new_x": XPos.LMARGIN, "new_y": YPos.NEXT}


class _ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.set_xy(10, 7)
        self.cell(0, 10, "HealthSense AI", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_font("Helvetica", "", 10)
        self.set_xy(10, 17)
        self.cell(0, 6, "AI-Generated Health Risk Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_xy(10, 32)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def get_recommendations(prediction: int) -> list:
    if prediction == 1:
        return [
            "Consult a licensed healthcare professional promptly for further evaluation.",
            "Schedule confirmatory diagnostic laboratory tests.",
            "Adopt a balanced, low-sugar / low-sodium diet as appropriate.",
            "Increase regular physical activity under medical guidance.",
            "Monitor key vitals regularly and track changes over time.",
        ]
    return [
        "Maintain your current healthy lifestyle and balanced nutrition.",
        "Continue routine annual health checkups.",
        "Stay physically active and manage stress levels.",
        "Report any new or worsening symptoms to your doctor promptly.",
    ]


def _section_title(pdf, text):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*ACCENT)
    pdf.set_x(10)
    pdf.cell(0, 9, text, **NEXT_LINE)
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "", 10)


def _kv_table(pdf, items):
    col_w = 95
    for i, (k, v) in enumerate(items):
        pdf.set_x(10)
        fill_color = (245, 247, 250) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*fill_color)
        pdf.cell(col_w, 7, str(k), border=0, fill=True)
        pdf.cell(col_w, 7, str(v), border=0, fill=True, **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(4)


def _disclaimer(pdf, text=None):
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.set_x(10)
    pdf.multi_cell(
        0, 5,
        text or (
            "Disclaimer: This report is generated by an AI/ML model for informational "
            "purposes only and does not constitute medical advice or diagnosis. Always "
            "consult a licensed healthcare professional for medical decisions."
        ),
        **NEXT_LINE,
    )


def generate_patient_report_pdf(disease: str, patient_report: dict, symptom_answers: dict) -> bytes:
    """PDF for the Patient Report: patient details, symptoms, AI risk
    prediction, risk level, confidence, recommended specialist and
    appointment suggestion. Never shows raw dataset columns/ML features."""
    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 10, f"Patient Report - {pretty(disease)} Screening", **NEXT_LINE)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Report ID: {patient_report['patient_report_id']}", **NEXT_LINE)
    pdf.cell(0, 6, datetime.datetime.now().strftime("Generated on %B %d, %Y at %H:%M"), **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(4)

    _section_title(pdf, "Patient Details")
    _kv_table(pdf, [
        ("Name", patient_report.get("patient_name", "Anonymous Patient")),
        ("Age", patient_report.get("age", "-")),
        ("Gender", patient_report.get("gender", "-")),
        ("Disease Screened", pretty(disease)),
    ])

    _section_title(pdf, "Symptoms & Health Details Provided")
    _kv_table(pdf, list(symptom_answers.items()))

    is_high = patient_report["risk_level"] == "High"
    color = DANGER if is_high else (SAFE if patient_report["risk_level"] == "Low" else (230, 160, 40))
    risk_pct = patient_report["risk_percent"]
    conf_pct = patient_report["confidence_percent"]

    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_x(10)
    pdf.cell(
        0, 12,
        f"  {patient_report['risk_level'].upper()} RISK   |   AI Risk Prediction: {risk_pct}%   |   Confidence: {conf_pct}%",
        fill=True, **NEXT_LINE,
    )
    pdf.set_x(10)
    pdf.ln(4)

    _section_title(pdf, "Recommendation")
    _kv_table(pdf, [
        ("Recommended Specialist", patient_report["recommended_specialist"]),
        ("Appointment Suggestion", patient_report["appointment_suggestion"]),
    ])

    _disclaimer(
        pdf,
        "Disclaimer: This Patient Report is generated by an AI/ML disease-prediction "
        "model for informational and screening purposes only. It is not a medical "
        "diagnosis. Please share this report with a licensed doctor for review.",
    )
    return bytes(pdf.output())


def generate_doctor_report_pdf(patient_report: dict, doctor_report: dict) -> bytes:
    """PDF for the Doctor Report: final diagnosis, demo prescription,
    lifestyle advice, follow-up date and doctor notes, extending the
    linked Patient Report's AI prediction."""
    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    disease = patient_report["disease"]
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 10, f"Doctor Report - {pretty(disease)}", **NEXT_LINE)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Doctor Report ID: {doctor_report['doctor_report_id']}", **NEXT_LINE)
    pdf.cell(0, 6, f"Linked Patient Report ID: {patient_report['patient_report_id']}", **NEXT_LINE)
    pdf.cell(0, 6, datetime.datetime.now().strftime("Generated on %B %d, %Y at %H:%M"), **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(4)

    _section_title(pdf, "Patient & AI Prediction Summary")
    _kv_table(pdf, [
        ("Patient Name", patient_report.get("patient_name", "Anonymous Patient")),
        ("Disease Screened", pretty(disease)),
        ("AI Risk Prediction", f"{doctor_report['ai_risk_percent']}%"),
        ("AI Risk Level", doctor_report["ai_risk_level"]),
        ("AI Confidence", f"{doctor_report['ai_confidence_percent']}%"),
    ])

    _section_title(pdf, "Diagnostic Tests Suggested (Demo)")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("diagnostic_tests_suggested") or "None recorded", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Test Observations (Demo)")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("test_observations") or "None recorded", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Final Diagnosis")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("final_diagnosis") or "Not specified", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Demo Prescription")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("demo_prescription") or "Not specified", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Lifestyle Advice")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("lifestyle_advice") or "Not specified", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Follow-up Date")
    pdf.set_x(10)
    pdf.cell(0, 7, str(doctor_report.get("follow_up_date") or "Not scheduled"), **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(2)

    _section_title(pdf, "Doctor Notes")
    pdf.set_x(10)
    pdf.multi_cell(0, 6, doctor_report.get("doctor_notes") or "-", **NEXT_LINE)
    pdf.set_x(10)
    pdf.ln(4)

    _disclaimer(
        pdf,
        "Disclaimer: This Demo Prescription is a placeholder entered by the "
        "reviewing user for demonstration purposes only. It is not a real, "
        "pharmacist-verified prescription and must never be used for actual "
        "treatment. Always follow a licensed physician's official prescription.",
    )
    return bytes(pdf.output())
